(function(){
const PROFILE='prs-research-profile-v1',SESSION='prs-session-v1',CART='prs-cart-v1',COOKIE='prs-cookie-choice';
function read(k,fallback){try{return JSON.parse(localStorage.getItem(k))??fallback}catch{return fallback}}
function write(k,v){localStorage.setItem(k,JSON.stringify(v))}
function escapeHtml(v){return String(v||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
window.openPrivacy=function(){document.querySelector('.cookie')?.classList.add('show')};
window.setCookies=function(v){localStorage.setItem(COOKIE,v);document.querySelector('.cookie')?.classList.remove('show')};
window.logoutResearch=function(){localStorage.removeItem(SESSION);location.href='index.html'};
window.stepQty=function(btn,delta){const input=btn.parentElement.querySelector('input');const n=Math.max(1,Math.min(99,(parseInt(input.value,10)||1)+delta));input.value=n};
window.toggleResearch=function(btn){btn.classList.toggle('open');btn.nextElementSibling?.classList.toggle('open')};
window.addProductToCart=function(btn){if(!read(SESSION,null)){location.href='login.html?next=catalog.html';return}const card=btn.closest('[data-product-card]');const qty=parseInt(card.querySelector('.qty input')?.value||'1',10);const item={sku:card.dataset.sku,name:card.dataset.name||card.dataset.sku,price:Number(card.dataset.price||0),lot:card.dataset.lot||'Pending lot assignment',qty};let cart=read(CART,[]);const found=cart.find(x=>x.sku===item.sku&&x.lot===item.lot);if(found)found.qty+=qty;else cart.push(item);write(CART,cart);btn.textContent='Added';setTimeout(()=>btn.textContent='Add to Cart',900);updateCartCount()};
function updateCartCount(){const n=read(CART,[]).reduce((s,x)=>s+x.qty,0);document.querySelectorAll('[data-cart-count]').forEach(el=>el.textContent=n)}
function redFlag(text){const s=String(text||'').toLowerCase();return ['personal use','human use','inject','injection','dose','dosing','weight loss','lose weight','healing','injury','anti-aging','anti aging','bodybuilding','muscle gain','treatment','patient','therapy for me','use on myself','use myself'].some(x=>s.includes(x))}
window.submitResearchApplication=function(form){const msg=document.getElementById('applicationMsg');const data=Object.fromEntries(new FormData(form).entries());const checks=[...form.querySelectorAll('[data-attest]')];if(checks.some(x=>!x.checked)){msg.textContent='All research-use attestations are required.';msg.style.color='#d9b95c';return false}if(redFlag(data.researchPurpose)){msg.textContent='This request describes personal, human-use, or treatment intent and cannot be approved through the research-access pathway.';msg.style.color='#d9b95c';return false}const id='PRS-'+new Date().toISOString().slice(0,7).replace('-','')+'-'+Math.random().toString(36).slice(2,8).toUpperCase();const profile={id,email:data.email,organization:data.organization,entityType:data.entityType,role:data.role,address:data.address,researchArea:data.researchArea,researchModel:data.researchModel,researchPurpose:data.researchPurpose,certifiedAt:new Date().toISOString(),termsVersion:'2026-08-17'};write(PROFILE,profile);write(SESSION,{id,email:data.email,startedAt:new Date().toISOString()});msg.innerHTML='Research account created. Your prototype Access ID is <b>'+escapeHtml(id)+'</b>. Redirecting to the member catalog…';msg.style.color='#4dd4c7';setTimeout(()=>location.href='catalog.html',900);return false};
window.memberLogin=function(form){const msg=document.getElementById('loginMsg');const profile=read(PROFILE,null);const data=Object.fromEntries(new FormData(form).entries());if(profile&&String(profile.email).toLowerCase()===String(data.email).toLowerCase()&&String(profile.id).toUpperCase()===String(data.accessId).trim().toUpperCase()){write(SESSION,{id:profile.id,email:profile.email,startedAt:new Date().toISOString()});const next=new URLSearchParams(location.search).get('next');location.href=next&&/^[a-z0-9-]+\.html$/i.test(next)?next:'catalog.html';return false}msg.textContent='No matching research account was found on this browser. Create a research account first.';msg.style.color='#d9b95c';return false};
function protect(){if(document.body.dataset.researchProtected==='true'&&!read(SESSION,null)){const next=location.pathname.split('/').pop()||'catalog.html';location.replace('login.html?next='+encodeURIComponent(next));return false}return true}
function hydrateMember(){const p=read(PROFILE,null);document.querySelectorAll('[data-member-name]').forEach(el=>el.textContent=p?.organization||'Research Member');document.querySelectorAll('[data-access-id]').forEach(el=>el.textContent=p?.id||'—')}
function renderCheckout(){const host=document.getElementById('cartItems');if(!host)return;const cart=read(CART,[]);if(!cart.length){host.innerHTML='<div class="notice">Your research cart is empty. <a href="catalog.html">Return to catalog.</a></div>';document.getElementById('orderTotal').textContent='$0.00';return}let total=0;host.innerHTML=cart.map(x=>{const line=x.price*x.qty;total+=line;return '<div class="data-row"><span>'+escapeHtml(x.name)+' × '+x.qty+'<br><small>'+escapeHtml(x.sku)+' · '+escapeHtml(x.lot)+'</small></span><b>$'+line.toFixed(2)+'</b></div>'}).join('');document.getElementById('orderTotal').textContent='$'+total.toFixed(2)}
window.submitResearchOrder=function(form){const msg=document.getElementById('orderMsg');const attest=form.querySelector('[name=orderAttest]');if(!attest?.checked){msg.textContent='Confirm the research-use order certification before continuing.';msg.style.color='#d9b95c';return false}if(!read(CART,[]).length){msg.textContent='Your cart is empty.';msg.style.color='#d9b95c';return false}const ref='PRS-ORDER-'+Date.now().toString().slice(-8);msg.innerHTML='<b>'+ref+'</b> created in this prototype. Payment processing and live fulfillment are not connected yet.';msg.style.color='#4dd4c7';return false};
if(!localStorage.getItem(COOKIE))document.querySelector('.cookie')?.classList.add('show');
if(!protect())return;hydrateMember();updateCartCount();renderCheckout();
})();